# EZCool 4x2 HDMI Matrix RS232 Control

# Find these in the manual or researched details
# This is setup to use a ESP 8622 UART connection, but can be configured for any device.
# EZCoolAV 4x2 Matrix - https://www.easycoolav.com/products/hdmi-matrix-4x2-matrix-4-in-2-out-18gbps-mx42hs

esphome:
  name: video-matrix-4x2
  friendly_name: Video Matrix 4x2
  includes:
    - uart_read_line_sensor.h

esp8266:
  board: esp01_1m

# Enable logging
logger:
    level: VERBOSE #makes uart stream available in esphome logstream
    baud_rate: 0 #disable uart logging over uart

###########This is where your ESP config lines go######




#################

captive_portal:
    
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 57600
  id: uart_bus

text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline"

######################################
# Button Control for matrix settings #
######################################

#################################
# HDMI Output 1 Input Selection #
#################################

button:
  - platform: template
    name: "Out1/In1"
    icon: mdi:hdmi-port
    id: out1_in1
    on_press:
      then:
        - uart.write: "EZS OUT1 VS IN1\r\n"
        - logger.log: "OUT_1 set to IN1"
  - platform: template
    name: "Out1/In2"
    icon: mdi:hdmi-port
    id: out1_in2
    on_press:
      then:
        - uart.write: "EZS OUT1 VS IN2\r\n"
        - logger.log: "OUT_1 set to IN2"
  - platform: template
    name: "Out1/In3"
    icon: mdi:hdmi-port
    id: out1_in3
    on_press:
      then:
        - uart.write: "EZS OUT1 VS IN3\r\n"
        - logger.log: "OUT_1 set to IN3"
  - platform: template
    name: "Out1/In4"
    icon: mdi:hdmi-port
    id: out1_in4
    on_press:
      then:
        - uart.write: "EZS OUT1 VS IN4\r\n"
        - logger.log: "OUT_1 set to IN4"

#################################
# HDMI Output 2 Input Selection #
#################################

  - platform: template
    name: "Out2/In1"
    icon: mdi:hdmi-port
    id: out2_in1
    on_press:
      then:
        - uart.write: "EZS OUT2 VS IN1\r\n"
        - logger.log: "OUT_2 set to IN1"
  - platform: template
    name: "Out2/In2"
    icon: mdi:hdmi-port
    id: out2_in2
    on_press:
      then:
        - uart.write: "EZS OUT2 VS IN2\r\n"
        - logger.log: "OUT_2 set to IN2"
  - platform: template
    name: "Out2/In3"
    icon: mdi:hdmi-port
    id: out2_in3
    on_press:
      then:
        - uart.write: "EZS OUT2 VS IN3\r\n"
        - logger.log: "OUT_2 set to IN3"
  - platform: template
    name: "Out2/In4"
    icon: mdi:hdmi-port
    id: out2_in4
    on_press:
      then:
        - uart.write: "EZS OUT2 VS IN4\r\n"
        - logger.log: "OUT_2 set to IN4"

#################################
# ALL HDMI Outs Input Selection #
#################################

  - platform: template
    name: "All/In1"
    icon: mdi:hdmi-port
    id: all_in1
    on_press:
      then:
        - uart.write: "EZS OUT0 VS IN1\r\n"
        - logger.log: "ALL_OUT set to IN1"
  - platform: template
    name: "All/In2"
    icon: mdi:hdmi-port
    id: all_in2
    on_press:
      then:
        - uart.write: "EZS OUT0 VS IN2\r\n"
        - logger.log: "ALL_OUT set to IN2"
  - platform: template
    name: "All/In3"
    id: all_in3
    icon: mdi:hdmi-port
    on_press:
      then:
        - uart.write: "EZS OUT0 VS IN3\r\n"
        - logger.log: "ALL_OUT set to IN3"
  - platform: template
    name: "All/In4"
    icon: mdi:hdmi-port
    id: all_in4
    on_press:
      then:
        - uart.write: "EZS OUT0 VS IN4\r\n"
        - logger.log: "ALL_OUT set to IN4"

