# Insert Below "captive_portal" in ESPHome

remote_transmitter:
  pin:
    number: GPIO12
#    inverted: True
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Vizio Power On"
    on_press:
      - remote_transmitter.transmit_nec:
          address: "0xFB04"
          command: "0xF708"

# The above is the raw output from the receiver, but parsed:
# Raw-data: 0xF708FB04
# The first 4 characters are the command
# The last 4 characters are the address
